### ISSUE TITLE
About Car Overturning

### ISSUE THREAD

**Issue by dianstudy** [reiniscimurs/DRL-robot-navigation#116]
hi,I followed your steps for training. At the beginning, the training was normal, but after certain episodes, it turned and overturned. May I ask if there is any solution？

**Comment by reiniscimurs** [comment]
Hi,

Please provide detailed description of the issue. Preferably with images and/or videos.

**Comment by dianstudy** [comment]
> Hi,
> 
> Please provide detailed description of the issue. Preferably with images and/or videos.

ok.like this video?
https://github.com/reiniscimurs/DRL-robot-navigation/assets/99256528/535bd7ff-87b3-43a7-9107-ca2b56c9a2be

and this is training situation.
![IMG_20240223_163241.jpg](https://github.com/reiniscimurs/DRL-robot-navigation/assets/99256528/3abe5be4-ca22-4799-baea-db18c541b21b)

**Comment by reiniscimurs** [comment]
Most likely your robot is not spawning properly after a reset and its wheel doesn't spawn in time before the robot starts moving. You can try to confirm this visually by looking at robot wheels at the reset time.

You can also try increasing the wait time in the reset function so that robot stays still for longer after reset: https://github.com/reiniscimurs/DRL-robot-navigation/blob/101ed8eaba77b9f447e3d57cc71518cfedb7f65c/TD3/velodyne_env.py#L279
