### ISSUE TITLE
Not found TF frame Odom

### ISSUE THREAD

**Issue by yuqikong** [reiniscimurs/DRL-robot-navigation#25]
Have r1/Odom, but rviz prompt not found odom, Please what should I do to solve this problem?
![EAD2D5BC-6A5E-4068-B4F6-1847372C1C64](https://user-images.githubusercontent.com/64312086/184543013-e4fb0eef-16ee-4e41-822c-d89292b88eac.jpeg)

**Comment by reiniscimurs** [comment]
Hi,

Please provide a little bit more detail.
Mainly, your system setup, ros version, repo version (melodic or noetic) and a full image of the graph.

**Comment by yuqikong** [comment]
![1660529377339](https://user-images.githubusercontent.com/64312086/184566366-7587935e-2504-4b2c-845a-fb070ccb0466.jpg)
![1660529377308](https://user-images.githubusercontent.com/64312086/184566391-1a6370ce-0ee2-4727-ae84-f5ca35809f0d.jpg)
![1660529377329](https://user-images.githubusercontent.com/64312086/184566398-ceab6e4c-d83f-49e3-b0c8-0c1d4d4c0ef2.jpg)
![1111](https://user-images.githubusercontent.com/64312086/184566514-b0e1d64e-1ae9-421c-a6f0-c777e5543838.png)

**Comment by yuqikong** [comment]
I think r1/odom should be changed to odom, but I don't know where to change it.

**Comment by reiniscimurs** [comment]
Hi,

I see you are using the Melodic version of the repo on a Kinetic ROS version. There are differences in how things are handled between versions. I cannot be sure that it is happening in this case, but that may cause an issue.

The issue seems to be that there is no link created between r1/odom and base_link. This is explicitly established in https://github.com/reiniscimurs/DRL-robot-navigation/blob/a89e460902e461ee55535180f5ad0d9a5630ae11/catkin_ws/src/multi_robot_scenario/launch/multi_robot_scenario.launch#L19

There should not be a link between r1/odom and r1/base_link as it is in your graph, so make sure all the installation steps were carried out properly (with changed locations, if there were any) and that ros is not calling any other `multi_robot_scenario` package.

You could also explicitly create a link between r1/base_link and base_link and see if that helps.
You can do that by adding 
`<node pkg="tf" type="static_transform_publisher" name="base_to_base_r1"
     args="0.0 -0.0 0.0 0.0 0.0 0.0 base_link r1/base_link 200" />`

right after the previously mentioned code and see if a link is established.
If nothing changes, something might be off with your `static_transform_publisher` node.

**Comment by yuqikong** [comment]
I get it, thank you very much.

**Comment by tqlblzj** [comment]
> I get it, thank you very much.

i meet the same error,how did you fix it
